# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ns-dawn-azure-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_beea54b1a7db4242b448929cdf56e587 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ec857e5d69b54c79a6eb14d28ff7a3ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_beea54b1a7db4242b448929cdf56e587 }}/oven/bun:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ns-dawn-azure-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_822ed1529e3f47649bd9116d8b19a572 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_beea54b1a7db4242b448929cdf56e587 }}/oven/bun:${{ github.sha }}'